FROM anyscale/ray:0.8.7
ARG VERSION
LABEL maintainer="Anyscale Academy <academy@anyscale.com>"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ADD academy-base /root/academy-base
RUN ls -al /root/academy-base

# RUN /root/anaconda3/bin/conda init bash
# RUN echo 'PATH=/root/anaconda3/envs/anyscale-academy/bin:$PATH' >> /root/.bashrc
RUN echo 'conda deactivate; conda activate anyscale-academy' >> /root/.bashrc

#RUN /root/anaconda3/bin/conda update -n base -c defaults conda
# Install in the base conda installation.
RUN conda install -y nodejs
RUN conda install -y ipywidgets

# Create the academy environment:
RUN /root/anaconda3/bin/conda env create -f /root/academy-base/environment-docker.yml
RUN /root/anaconda3/bin/jupyter labextension install "@pyviz/jupyterlab_pyviz"
RUN /root/anaconda3/bin/jupyter labextension update --all
RUN /root/anaconda3/bin/jupyter lab build
RUN /root/anaconda3/bin/conda clean --all
