FROM deanwampler/academy-base:latest
ARG VERSION
LABEL maintainer="Anyscale Academy <academy@anyscale.com>"

ADD academy-all/academy-$VERSION       /root/academy-$VERSION
RUN ls -al /root/academy-$VERSION